export const ARTICLES_LOADED = 'ARTICLES_LOADED';

export const WEATHER_REQUESTED = 'WEATHER_REQUESTED';
export const WEATHER_LOADED = 'WEATHER_LOADED';
export const WEATHER_ERROR = 'WEATHER_ERROR';
export const CONDITION_LOADED = 'CONDITION_LOADED';
export const NEXT_DAYS_TEMP_LOADED = 'NEXT_DAYS_TEMP_LOADED';
export const WEATHER_INFO_LOADED = 'WEATHER_INFO_LOADED';
export const DAYTIME_LOADED = 'DAYTIME_LOADED';
export const DATE_LOADED = 'DATE_LOADED';

export const LOCATION_REQUESTED = 'LOCATION_REQUESTED';
export const LOCATION_LOADED = 'LOCATION_LOADED';
export const LOCATION_ERROR = 'LOCATION_ERROR';
export const CRDS_REQUESTED = 'CRDS_REQUESTED';
export const CRDS_LOADED = 'CRDS_LOADED';
export const LAT_LOADED = 'LAT_LOADED';
export const LON_LOADED = 'LON_LOADED';

export const SET_TEMPRETURE = 'SET_TEMPRETURE';
export const SET_LANGUAGE = 'SET_LANGUAGE';
export const SET_INPUT_TEXT = 'SET_INPUT_TEXT';
export const DATA_REQUESTED = 'DATA_REQUESTED';
export const DATA_LOADED = 'DATA_LOADED';
export const DATA_ERROR = 'DATA_ERROR';
export const SET_VOICE = 'SET_VOICE';

export const IMAGE_LOADED = 'IMAGE_LOADED';
export const IMAGE_REQUESTED = 'IAMGE_REQUESTED';
export const IMAGE_ERROR = 'IMAGE_ERROR';
